#if !macro
import physics.math.Math;
import physics.math.Vec3;
import physics.math.Vec4;
import physics.math.Quat;
import physics.math.Mat;
import physics.math.Plane;
import physics.math.ScaleHelper;
import physics.collision.*;
import physics.collision.shapes.*;
import physics.collision.shapes.ConvexShape;
import physics.collision.shapes.Shape;
import physics.collision.AABB;
import physics.collision.PhysicsWorld;
import physics.collision.Collector;
import physics.collision.narrowphase.*;
import physics.collision.broadphase.*;
import physics.utils.*;
import physics.utils.PhysicsContainer;
#end
